default: &default
  adapter: postgresql
  encoding: utf8
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:
  port: 
  username:
  password:

development:
  <<: *default
  database: itutor_development

test:
  <<: *default
  database: itutor_test

production:
  <<: *default
  database: itutor_production
